version: '3.8'

services:
  db:
    container_name: postgres-cdn
    image: postgis/postgis:15-3.3
    restart: on-failure
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data/

  api:
    container_name: api-cdn
    build: .
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - 8000:8000
    command: [ "./api.sh" ]
    restart: on-failure
    depends_on:
      - db