"""create cities

Revision ID: 94cdbe334dfa
Revises: 
Create Date: 2023-04-20 13:56:10.711117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94cdbe334dfa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cities',
    sa.Column('lat', sa.DECIMAL(precision=10, scale=8), nullable=False),
    sa.Column('lon', sa.DECIMAL(precision=11, scale=8), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('lat', 'lon')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cities')
    # ### end Alembic commands ###
